export interface IUser {
  avatar_url: "https://avatars.githubusercontent.com/u/58779341?v=4";
  bio: "Programador iniciante com interesses em Front e Back-End  ";
  blog: "https://dubcom.github.io/curriculo/";
  company: null;
  created_at: "2020-03-21T02:16:03Z";
  email: null;
  events_url: "https://api.github.com/users/dubcom/events{/privacy}";
  followers: 10;
  followers_url: "https://api.github.com/users/dubcom/followers";
  following: 9;
  following_url: "https://api.github.com/users/dubcom/following{/other_user}";
  gists_url: "https://api.github.com/users/dubcom/gists{/gist_id}";
  gravatar_id: "";
  hireable: null;
  html_url: "https://github.com/dubcom";
  id: 62454440;
  location: "Florianópolis - SC";
  login: "dubcom";
  name: "Marcos Antonio ";
  node_id: "MDQ6VXNlcjYyNDU0NDQw";
  organizations_url: "https://api.github.com/users/dubcom/orgs";
  public_gists: 0;
  public_repos: 15;
  received_events_url: "https://api.github.com/users/dubcom/received_events";
  repos_url: "https://api.github.com/users/dubcom/repos";
  site_admin: false;
  starred_url: "https://api.github.com/users/dubcom/starred{/owner}{/repo}";
  subscriptions_url: "https://api.github.com/users/dubcom/subscriptions";
  twitter_username: null;
  type: "User";
  updated_at: "2022-01-03T08:00:54Z";
  url: "https://api.github.com/users/dubcom";
}
